### ISSUE TITLE
enable langfuse ui support watsonx

### ISSUE THREAD

**Issue by gyliu513** [gyliu513/langX101#61]
```
trying to create observation for generation, project  clog5k8kn0000ns3b59z856gi , body: {
  “id”: “9013fb82-a78b-41c7-8d79-4084ac0912fe”,
  “traceId”: “Watsonx-generation”,
  “name”: “Watsonx-generation-xxxxxxx”,
  “startTime”: “2023-11-01T15:55:39.310827-04:00",
  “metadata”: {},
  “level”: “DEFAULT”,
  “statusMessage”: null,
  “endTime”: “2023-11-01T15:55:40.266009-04:00",
  “model”: “google/flan-ul2",
  “modelParameters”: {},
  “prompt”: “What is 1 + 1?“,
  “completion”: “oooooook”,
  “usage”: null
}
Unknown model provider google/flan-ul2
Unknown model provider google/flan-ul2
```

**Comment by gyliu513** [comment]
check openai as an example https://github.com/langfuse/langfuse/blob/main/src/features/ingest/lib/usage.ts#L33

**Comment by huang-cn** [comment]
@gyliu513 I've checked the langfuse code, only when calling `langfuse.generation` without usage data, langfuse will attempt to count the token from `prompt` based on the model type. Since we will be passing the usage to `langfuse.generation`, there won't be any issue.
https://github.com/langfuse/langfuse/blob/main/src/pages/api/public/generations.ts#L152-L167
